--shutdown immediate;
--startup mount;
--alter database archivelog;
--alter database open;

ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (PRIMARY
KEY, UNIQUE INDEX) COLUMNS;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;

create tablespace rao_tbs datafile '/u01/app/oracle/oradata/xe/rao01.dbf'
size 128M
autoextend on next 64M maxsize unlimited
extent management local uniform size 1M
segment space management auto;

CREATE USER RAUSER PROFILE "DEFAULT" IDENTIFIED
BY "Sybase123" DEFAULT TABLESPACE "RAO_TBS" ACCOUNT
UNLOCK;
ALTER USER RAUSER QUOTA UNLIMITED ON RAO_TBS;   

GRANT ALTER ANY PROCEDURE TO RAUSER;
GRANT ALTER ANY TABLE TO RAUSER;
GRANT ALTER SESSION TO RAUSER;
GRANT ALTER SYSTEM TO RAUSER;
GRANT CONNECT TO RAUSER;
GRANT CREATE PROCEDURE TO RAUSER;
GRANT CREATE PUBLIC SYNONYM TO RAUSER;
GRANT CREATE SESSION TO RAUSER;
GRANT CREATE TABLE TO RAUSER;
GRANT DROP ANY PROCEDURE TO RAUSER;
GRANT DROP ANY TABLE TO RAUSER;
GRANT DROP PUBLIC SYNONYM TO RAUSER;
GRANT EXECUTE_CATALOG_ROLE TO RAUSER;
GRANT EXECUTE ON SYS.DBMS_FLASHBACK TO RAUSER;
GRANT EXECUTE ON SYS.DBMS_LOCK TO RAUSER;
GRANT RESOURCE TO RAUSER;
GRANT SELECT ANY TRANSACTION TO RAUSER;
GRANT SELECT_CATALOG_ROLE TO RAUSER;
GRANT SELECT ON SYS.ARGUMENT$ TO RAUSER;
GRANT SELECT ON SYS.ATTRIBUTE$ TO RAUSER;
GRANT SELECT ON SYS.CCOL$ TO RAUSER;
GRANT SELECT ON SYS.CDEF$ TO RAUSER;
GRANT SELECT ON SYS.COL$ TO RAUSER;
GRANT SELECT ON SYS.COLLECTION$ TO RAUSER;
GRANT SELECT ON SYS.COLTYPE$ TO RAUSER;
GRANT SELECT ON SYS.CON$ TO RAUSER;
GRANT SELECT ON SYS.DEFERRED_STG$ TO RAUSER;
GRANT SELECT on SYS.ICOL$ TO RAUSER;
GRANT SELECT ON SYS.IND$ TO RAUSER;
GRANT SELECT ON SYS.INDCOMPART$ TO RAUSER;
GRANT SELECT ON SYS.INDPART$ TO RAUSER;
GRANT SELECT ON SYS.INDSUBPART$ TO RAUSER;
GRANT SELECT ON SYS.LOB$ TO RAUSER;
GRANT SELECT ON SYS.LOBCOMPPART$ TO RAUSER;
GRANT SELECT ON SYS.LOBFRAG$ TO RAUSER;
GRANT SELECT ON SYS.MLOG$ TO RAUSER;
GRANT SELECT ON SYS.NTAB$ TO RAUSER;
GRANT SELECT ON SYS.OBJ$ TO RAUSER;
GRANT SELECT ON SYS.OPQTYPE$ TO RAUSER;
GRANT SELECT ON SYS.v_$database TO RAUSER;
GRANT SELECT ON SYS.REDEF_OBJECT$ TO RAUSER;
GRANT ADMINISTER DATABASE TRIGGER TO RAUSER;
GRANT CREATE ANY PROCEDURE TO RAUSER;
GRANT SELECT ON SYS.PROCEDUREINFO$ TO RAUSER;
GRANT SELECT ON SYS.RECYCLEBIN$ TO RAUSER;
GRANT SELECT ON SYS.SEG$ TO RAUSER;
GRANT SELECT ON SYS.SEQ$ TO RAUSER;
GRANT SELECT ON SYS.SNAP$ TO RAUSER;
GRANT SELECT ON SYS.TS$ TO RAUSER;
GRANT SELECT ON SYS.TYPE$ TO RAUSER;
GRANT SELECT ON SYS.USER$ TO RAUSER;
GRANT SELECT ON SYS.PARTOBJ$ TO RAUSER;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO RAUSER;
GRANT SELECT ON V_$LOGMNR_LOGS TO RAUSER;
GRANT SELECT ON SYS.TAB$ TO RAUSER;
GRANT SELECT ON SYS.TABPART$ TO RAUSER;
GRANT SELECT ON SYS.TABCOMPART$ TO RAUSER;
GRANT SELECT ON SYS.TABSUBPART$ TO RAUSER;
GRANT UNLIMITED TABLESPACE TO RAUSER;


BEGIN
DBMS_STREAMS_AUTH.GRANT_ADMIN_PRIVILEGE( grantee =>
'RAUSER');
END;
/

ALTER USER RAUSER QUOTA UNLIMITED ON USERS;
grant "DBA" to RAUSER;
